'use client'

import Image from 'next/image'
import { useState } from 'react'
import { ArrowRight, CarFront, Check, Clock3, LockKeyhole, MapPin, ShieldCheck, Star, UserRound, WalletCards } from 'lucide-react'

type View = 'home' | 'history' | 'membership' | 'driver-application'

const plans = [
  { name: 'Básica', price: 'Gratis', benefits: ['Tarifa estándar', 'Soporte en horario laboral'] },
  { name: 'Premium', price: '$1.999 / mes', benefits: ['15% de descuento', 'Soporte prioritario', 'Cancelación flexible'] },
  { name: 'VIP', price: '$4.999 / mes', benefits: ['25% de descuento', 'Conductor preferido', 'Atención 24/7'] },
]

export default function BearRideApp() {
  const [view, setView] = useState<View>('home')
  const [destination, setDestination] = useState('')
  const [rideRequested, setRideRequested] = useState(false)
  const [applicationSent, setApplicationSent] = useState(false)
  const [toast, setToast] = useState('')
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2800) }

  return <main className="min-h-screen bg-background text-foreground lg:flex">
    <aside className="hidden w-72 shrink-0 flex-col border-r border-border bg-card p-7 lg:flex">
      <Brand />
      <div className="mt-14 flex items-center gap-3 rounded-2xl bg-secondary p-3"><Image src="/passenger-icon.png" alt="Pasajero" width={44} height={44} className="rounded-xl" /><div><p className="text-sm font-bold">Juan García</p><p className="text-xs text-muted-foreground">Pasajero Premium</p></div></div>
      <nav className="mt-8 flex flex-col gap-2" aria-label="Navegación principal"><NavItem icon={MapPin} label="Solicitar viaje" active={view === 'home'} onClick={() => setView('home')} /><NavItem icon={Clock3} label="Tus viajes" active={view === 'history'} onClick={() => setView('history')} /><NavItem icon={Star} label="Membresía" active={view === 'membership'} onClick={() => setView('membership')} /></nav>
      <div className="mt-auto rounded-2xl bg-foreground p-5 text-background"><ShieldCheck className="mb-6 size-6 text-primary" /><p className="font-serif text-xl leading-tight">Tu viaje,<br />en buenas manos.</p><p className="mt-3 text-xs leading-5 opacity-70">Conductores verificados y soporte 24/7.</p></div>
    </aside>
    <section className="relative min-h-screen flex-1 overflow-hidden"><header className="flex items-center justify-between border-b border-border/70 bg-background/90 px-5 py-5 backdrop-blur lg:px-10"><div className="lg:hidden"><Brand /></div><div className="ml-auto flex items-center gap-3"><span className="hidden rounded-full border border-border bg-card px-3 py-2 text-xs font-semibold sm:block">Argentina · ARS</span><button onClick={() => notify('Tu sesión está protegida')} className="flex items-center gap-2 rounded-full border border-border bg-card px-3 py-2 text-xs font-bold"><LockKeyhole className="size-3.5" /> Cuenta segura</button></div></header>
      <div className="mx-auto max-w-6xl p-5 lg:p-10"><div className="mb-8 flex items-end justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-primary">Panel de pasajero</p><h1 className="mt-2 font-serif text-4xl tracking-tight lg:text-5xl">{view === 'membership' ? 'Elegí tu membresía.' : view === 'history' ? 'Tus viajes.' : view === 'driver-application' ? 'Conducí con BearRide.' : '¿A dónde vamos?'}</h1><p className="mt-2 max-w-lg text-sm leading-6 text-muted-foreground">Movilidad simple, segura y cercana para cada trayecto.</p></div><button onClick={() => setView('driver-application')} className="hidden items-center gap-2 rounded-xl border border-border bg-card px-4 py-3 text-sm font-bold transition hover:border-primary sm:flex">Quiero ser conductor <ArrowRight className="size-4" /></button></div>
        {view === 'home' && <PassengerHome destination={destination} setDestination={setDestination} requested={rideRequested} onRequest={() => { if (!destination) return notify('Ingresá un destino para continuar'); setRideRequested(true); notify('Buscando un conductor cercano') }} />}
        {view === 'history' && <History />}
        {view === 'membership' && <Membership onSelect={(name) => notify(`Transferencia iniciada para ${name}`)} />}
        {view === 'driver-application' && <DriverApplication sent={applicationSent} onSubmit={() => { setApplicationSent(true); notify('Solicitud enviada para revisión') }} />}
        <div className="mt-8 grid gap-5 md:grid-cols-2"><Image src="/bearride-download-banner.png" alt="Descargá BearRide" width={1290} height={560} className="h-40 w-full rounded-2xl object-cover" /><Image src="/safety-banner.png" alt="Viajá con seguridad" width={720} height={380} className="h-40 w-full rounded-2xl object-cover" /></div>
      </div>{toast && <div role="status" className="fixed bottom-5 left-1/2 z-50 -translate-x-1/2 rounded-full bg-foreground px-5 py-3 text-sm font-semibold text-background shadow-xl">{toast}</div>}
    </section>
  </main>
}

function PassengerHome({ destination, setDestination, requested, onRequest }: any) { return <div className="grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><div className="relative min-h-[420px] overflow-hidden rounded-[28px] border border-border bg-[#dce8df] shadow-sm"><div className="map-grid absolute inset-0 opacity-80" /><div className="road road-one" /><div className="road road-two" /><div className="park park-one" /><div className="park park-two" /><div className="route-line" /><div className="pin pin-start"><div className="pin-dot" /></div><div className="pin pin-end"><MapPin className="size-5 fill-primary text-primary-foreground" /></div><div className="absolute left-5 top-5 rounded-full bg-card/90 px-3 py-2 text-xs font-semibold shadow-sm">Google Maps · modo demo</div>{requested && <div className="absolute bottom-5 left-5 rounded-2xl bg-foreground px-4 py-3 text-sm font-semibold text-background">Conductor asignado · llega en 3 min</div>}</div><div className="rounded-[28px] border border-border bg-card p-5 shadow-sm lg:p-7"><div className="flex items-center gap-3"><Image src="/passenger-icon.png" alt="Perfil pasajero" width={48} height={48} className="rounded-xl" /><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-primary">Hola, Juan</p><h2 className="mt-1 font-serif text-3xl">Planificá tu viaje</h2></div></div><div className="mt-7 flex flex-col gap-2"><label className="flex items-center gap-3 rounded-xl border border-border bg-secondary/50 p-3"><MapPin className="size-4 text-primary" /><input aria-label="Destino" value={destination} onChange={(e) => setDestination(e.target.value)} placeholder="¿A dónde vamos?" className="w-full bg-transparent text-sm outline-none placeholder:text-muted-foreground" /></label><div className="flex items-center gap-3 rounded-xl border border-border p-3 text-sm text-muted-foreground"><div className="size-2 rounded-full bg-primary" /> Av. Santa Fe 1450, Palermo</div></div><div className="mt-6 flex items-center justify-between border-t border-border pt-5"><div><p className="text-xs text-muted-foreground">Estimado BearRide</p><p className="text-2xl font-bold">$3.850</p></div><button onClick={onRequest} className="rounded-xl bg-primary px-5 py-3 text-sm font-bold text-primary-foreground">{requested ? 'Viaje activo' : 'Solicitar viaje'}</button></div></div></div> }
function History() { return <div className="grid gap-4 lg:max-w-3xl">{['Avenida Corrientes → Palermo', 'San Telmo → Puerto Madero', 'Recoleta → Belgrano'].map((ride, i) => <div key={ride} className="flex items-center gap-4 rounded-2xl border border-border bg-card p-5"><div className="flex size-10 items-center justify-center rounded-full bg-primary/15"><CarFront className="size-4 text-primary" /></div><div className="flex-1"><p className="text-sm font-semibold">{ride}</p><p className="mt-1 text-xs text-muted-foreground">{i ? 'Ayer, 18:40' : 'Hoy, 09:24'} · BearRide</p></div><p className="font-bold">${[3850, 4200, 3600][i].toLocaleString('es-AR')}</p></div>)}</div> }
function Membership({ onSelect }: any) { return <div className="grid gap-4 xl:grid-cols-3">{plans.map((plan, i) => <div key={plan.name} className={`flex flex-col rounded-2xl border p-6 ${i === 1 ? 'border-primary bg-primary/5 ring-1 ring-primary' : 'border-border bg-card'}`}><p className="text-sm font-bold text-primary">{plan.name}</p><p className="mt-4 font-serif text-3xl">{plan.price}</p><div className="my-6 flex flex-col gap-3">{plan.benefits.map((benefit) => <p key={benefit} className="flex gap-2 text-sm"><Check className="size-4 shrink-0 text-primary" />{benefit}</p>)}</div><button onClick={() => onSelect(plan.name)} className="mt-auto rounded-xl border border-primary px-4 py-3 text-sm font-bold text-primary">Elegir {plan.name}</button></div>)}</div> }
function DriverApplication({ sent, onSubmit }: any) { return <div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-[28px] bg-foreground p-7 text-background"><Image src="/driver-icon.png" alt="Conductor BearRide" width={110} height={110} className="rounded-2xl" /><h2 className="mt-7 font-serif text-3xl">Una comunidad de conductores seguros.</h2><p className="mt-3 text-sm leading-6 opacity-70">El acceso se habilita únicamente después de validar tu identidad y documentación.</p></div><div className="rounded-[28px] border border-border bg-card p-7"><h2 className="font-serif text-3xl">Postulación de conductor</h2><div className="mt-6 flex flex-col gap-3 text-sm">{['DNI frente y dorso', 'Registro de conducir vigente', 'Certificado de antecedentes penales', 'Cédula y seguro del vehículo'].map((item) => <div key={item} className="flex items-center gap-3 rounded-xl bg-secondary/60 p-4"><Check className="size-4 text-primary" />{item}<span className="ml-auto text-xs text-muted-foreground">Pendiente</span></div>)}</div><button disabled={sent} onClick={onSubmit} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-primary py-3 font-bold text-primary-foreground disabled:opacity-60">{sent ? 'Solicitud en revisión' : 'Enviar documentación'} <ArrowRight className="size-4" /></button><p className="mt-4 text-center text-xs text-muted-foreground">Un equipo de BearRide revisará tu solicitud antes de habilitar el panel.</p></div></div> }
function Brand() { return <div className="flex items-center gap-3"><Image src="/bearride-app-icon.png" alt="BearRide" width={42} height={42} className="rounded-xl" /><span className="font-serif text-2xl font-bold">Bear<span className="text-primary">Ride</span></span></div> }
function NavItem({ icon: Icon, label, active, onClick }: any) { return <button onClick={onClick} className={`flex items-center gap-3 rounded-xl px-4 py-3 text-sm font-semibold ${active ? 'bg-foreground text-background' : 'text-muted-foreground hover:bg-secondary hover:text-foreground'}`}><Icon className="size-4" />{label}</button> }

export { Brand }
