import Image from 'next/image'
import type { ReactNode } from 'react'
import { BadgeCheck, MapPinned, ShieldCheck } from 'lucide-react'

export default function AuthLayout({ children }: { children: ReactNode }) {
  return <main className="grid min-h-screen overflow-hidden bg-[#f8f6ef] lg:grid-cols-[1.05fr_.95fr]"><section className="relative hidden overflow-hidden bg-[#123f3a] p-12 text-background lg:flex lg:flex-col"><div className="absolute -left-24 -top-24 size-96 rounded-full bg-primary/30 blur-3xl" /><div className="absolute -bottom-32 -right-24 size-[30rem] rounded-full border-[70px] border-white/5" /><Image src="/bearride-logo-white.png" alt="BearRide" width={180} height={50} className="relative h-auto w-40" /><div className="relative my-auto max-w-lg"><p className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-2 text-xs font-bold uppercase tracking-[.16em] text-primary"><MapPinned className="size-3.5" />Formosa, Argentina</p><h2 className="mt-7 font-serif text-6xl leading-[.98]">Movete con<br /><em className="text-primary">confianza.</em></h2><p className="mt-7 max-w-md text-lg leading-8 text-background/70">Pedí, gestioná y seguí cada viaje desde una experiencia simple, segura y pensada para tu ciudad.</p><div className="mt-10 grid grid-cols-2 gap-3"><Feature icon={ShieldCheck} text="Conductores verificados" /><Feature icon={BadgeCheck} text="Tarifa clara antes de viajar" /></div></div><p className="relative text-sm text-background/45">© {new Date().getFullYear()} BearRide</p></section><section className="relative flex min-h-screen items-center justify-center p-5 sm:p-8"><div className="absolute left-0 top-0 h-2 w-full bg-primary lg:hidden" /><div className="w-full max-w-md">{children}</div></section></main>
}

function Feature({ icon: Icon, text }: { icon: typeof ShieldCheck; text: string }) { return <div className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/5 p-4 text-sm font-semibold"><Icon className="size-5 text-primary" />{text}</div> }
