import Link from 'next/link'
import { ArrowRight, Clock3, Heart, MapPin, ShieldCheck } from 'lucide-react'
import { AppHeader } from '@/components/navigation/app-header'
import { MapboxMap } from '@/components/map/mapbox-map'
import { requireProfile } from '@/lib/auth/session'

export const dynamic = 'force-dynamic'

export default async function PassengerPage() {
  const profile = await requireProfile()
  if (profile.role === 'DRIVER') return <main><AppHeader profile={profile} /><section className="mx-auto max-w-xl p-8"><h1 className="font-serif text-3xl">Esta cuenta es de conductor.</h1><Link className="mt-5 inline-block text-primary" href="/driver">Ir al panel de conductor</Link></section></main>
  return <main className="min-h-screen bg-[#f8f6ef]"><AppHeader profile={profile} /><section className="mx-auto flex max-w-7xl flex-col gap-6 p-4 sm:p-6 lg:p-10"><div className="grid gap-5 rounded-[2rem] bg-[#123f3a] p-6 text-background shadow-xl shadow-[#123f3a]/15 sm:p-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">Bienvenido/a, {profile.fullName.split(' ')[0]}</p><h1 className="mt-3 max-w-xl font-serif text-4xl leading-[.98] text-balance sm:text-5xl">Tu próximo viaje empieza acá.</h1><p className="mt-4 max-w-xl leading-7 text-background/70">Encontrá destinos, conocé la tarifa antes de confirmar y viajá con más tranquilidad.</p></div><Link href="/passenger/ride" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-primary px-5 py-3 font-bold text-primary-foreground shadow-lg shadow-black/20 transition hover:-translate-y-0.5">Pedir un viaje <ArrowRight className="size-4" /></Link></div><div className="grid gap-5 lg:grid-cols-[minmax(0,1.3fr)_minmax(18rem,.7fr)]"><div className="min-h-[26rem] lg:min-h-[33rem]"><MapboxMap /></div><div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-1"><QuickLink icon={MapPin} title="Pedir un viaje" detail="Elegí el destino y confirmá" href="/passenger/ride" accent /><QuickLink icon={Clock3} title="Tus viajes" detail="Consultá el estado e historial" href="/passenger/history" /><QuickLink icon={Heart} title="Favoritos" detail="Llegá más rápido a tus lugares" href="/passenger/favorites" /></div></div><div className="flex items-center gap-3 rounded-2xl border border-border bg-card p-4 text-sm text-muted-foreground"><span className="flex size-9 shrink-0 items-center justify-center rounded-xl bg-primary/15 text-primary"><ShieldCheck className="size-4" /></span><p><strong className="text-foreground">Tu seguridad primero.</strong> El viaje se solicita con una tarifa calculada en el servidor y conductores verificados.</p></div></section></main>
}

function QuickLink({ icon: Icon, title, detail, href, accent = false }: { icon: typeof MapPin; title: string; detail: string; href: string; accent?: boolean }) { return <Link href={href} className={`group flex min-h-36 flex-col rounded-2xl border p-5 transition hover:-translate-y-0.5 hover:shadow-lg ${accent ? 'border-primary bg-primary text-primary-foreground' : 'border-border bg-card hover:border-primary'}`}><Icon className="size-5" /><strong className="mt-auto">{title}</strong><span className={`mt-1 text-sm ${accent ? 'text-primary-foreground/70' : 'text-muted-foreground'}`}>{detail}</span></Link> }
